pipeline {
    agent any

    tools {
        maven 'maven-home'
    }
    stages {
        stage('Build maven') {
            steps {
                sh 'mvn --version'
                sh 'java -version'
                sh 'mvn clean install'
            }
        }
    }
}