pipeline {
    agent any

    tools {
        maven 'maven-home'
    }
    stages {
        stage('Build maven') {
            steps {
                dir('./micro-common') {
                    sh 'mvn clean install'
                }

                dir('./micro-user') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Deploy to VPS') {
            steps {
                echo 'Deploying and cleaning'
            }
        }
    }
}