server:
  port: 8083
logging:
  level:
    root: INFO
spring:
  application:
    name: micro-task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rain.db.elephantsql.com:5432/ohwweerk
    username: ohwweerk
    password: QINiYidMmQQesbfQjNOhxRZgw7ZhVlYp